server {
    listen ${PORT};
    server_name _;

    root /usr/share/nginx/html;
    index "Sri Velan Pasumai ERP.dc.html";

    location / {
        try_files $uri $uri/ /"Sri Velan Pasumai ERP.dc.html";
    }
}
